### ISSUE TITLE
Ошибки и недоступность к командам бота

### ISSUE THREAD

**Issue by Nalborr** [1MagicSweet/MafiaBot-public#1]
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
SLF4J: Defaulting to no-operation MDCAdapter implementation.
SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
[main] INFO JDA - Login Successful!
[JDA MainWS-ReadThread] INFO WebSocketClient - Connected to WebSocket
[JDA MainWS-ReadThread] INFO JDA - Finished Loading!

**Comment by 1MagicSweet** [comment]
> 
> 
> SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
> SLF4J: Defaulting to no-operation (NOP) logger implementation
> SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
> SLF4J: Failed to load class "org.slf4j.impl.StaticMDCBinder".
> SLF4J: Defaulting to no-operation MDCAdapter implementation.
> SLF4J: See http://www.slf4j.org/codes.html#no_static_mdc_binder for further details.
> [main] INFO JDA - Login Successful!
> [JDA MainWS-ReadThread] INFO WebSocketClient - Connected to WebSocket
> [JDA MainWS-ReadThread] INFO JDA - Finished Loading!

Команды бота достаются не из консоли
Сообщение выше - ([JDA MainWS-ReadThread] INFO JDA - Finished Loading!) означает, что бот успешно загрузился и готов работать

**Comment by 1MagicSweet** [comment]
Запусти джарник, пригласи бота на сервер и используй

**Comment by 1MagicSweet** [comment]
Closed.
